Repository ashutosh-rath02/git-re, pull requests merged in 2024-06, with the labels that each got.

#210 [Documentation]: Add npm run build and npm run start instructions to contributing.md
  CONTRIBUTING.md
Labels: GSSoC'24, level1, gssoc

#211 Moving border Button
  components/AuthButton.tsx
  components/Form.tsx
  components/ui/MagicButton.tsx
Labels: GSSoC'24, level2, gssoc

#207 fixed contributions and repositories bug in sidebar of resume
  components/Sidebar.tsx
  utils/resumeUtils.ts
Labels: GSSoC'24, level1, gssoc

#225 Fix: The landing page is having the button product hunt looking uneven #213
  app/page.tsx
Labels: GSSoC'24, level1, gssoc

#227 Extra section in navbar
  components/Hamburger.tsx
Labels: GSSoC'24, level1, gssoc

#239 [feat]: save the user rating in database
  LEARN.md
  utils/rating/action.ts
Labels: GSSoC'24, level3, gssoc

#245 [feat]: add leaderboard to navigation bar
  components/Hamburger.tsx
  components/navbar.tsx
Labels: level1, gssoc

#257 [Feature]: Crown for top three in leaderboard
  app/leaderboard/page.tsx
  components/leaderboard/crown.tsx
Labels: GSSoC'24, level2, gssoc

#255 [bug fixed]: ratelimit issue
  .env.example
  app/api/users/route.ts
  app/resume/[username]/view/page.tsx
  components/Form.tsx
  components/Resume.tsx
  utils/GithubAPI.ts
  utils/resumeUtils.ts
Labels: GSSoC'24, level2, gssoc

#265 [bug]: fixed image quality of profile photo on resume page
  components/new-resume.tsx
Labels: GSSoC'24, level1, gssoc

#267 enhancement: add top loading animation
  app/layout.tsx
  package.json
Labels: GSSoC'24, level2, gssoc

#277 feat: profile tracking
  components/ProfileTracking.tsx
  components/new-resume.tsx
  package-lock.json
Labels: GSSoC'24, level3, gssoc

#275 fix: blank website url in resume page
  components/new-resume.tsx
Labels: GSSoC'24, level1, gssoc

#286 [Bug]: Profile tracking is not scrollable
  app/globals.css
  components/ProfileTracking.tsx
Labels: GSSoC'24, level2, gssoc

#300 Website Background
  app/page.tsx
  components/navbar.tsx
  components/ui/hero-highlight.tsx
  package-lock.json
  package.json
  tailwind.config.ts
Labels: GSSoC'24, level2, gssoc

#311 Fix Described Issues
  components/Form.tsx
  components/ProfileTracking.tsx
  components/RecentGenerations.tsx
  components/footer.tsx
  components/navbar.tsx
Labels: GSSoC'24, level3, gssoc

#321 solves User is rate-limited by GitHub (issue324)
  app/api/users/route.ts
Labels: GSSoC'24, level2, gssoc

#323 fixed crowns issue in leaderboard
  app/leaderboard/page.tsx
Labels: GSSoC'24, level1, gssoc

#326 fixes: GitHub authenticated API calls
  components/ProfileTracking.tsx
  components/new-resume.tsx
Labels: GSSoC'24, level2, gssoc

#329 Compare feature (issue6)
  app/compare/action.ts
  app/compare/page.tsx
  components/Hamburger.tsx
  components/RadarChart.jsx
  components/navbar.tsx
  package-lock.json
  package.json
Labels: GSSoC'24, level3, gssoc

#334 feat: compare non exisiting user
  app/compare/action.ts
  app/compare/page.tsx
Labels: GSSoC'24, level2, gssoc
