Repository ashutosh-rath02/git-re, pull requests merged in 2024-07, with the labels that each got.

#342 [Documentation Update]: Update Table Creation SQL
  LEARN.md
Labels: GSSoC'24, level1, gssoc

#343 fixed: The "images.domains" configuration is deprecated. Please use "images.remotePatterns" configuration instead.
  next.config.js
Labels: GSSoC'24, level2, gssoc

#351 feat: add share button
  components/ShareBtn.tsx
  components/new-resume.tsx
Labels: GSSoC'24, level2, gssoc

#364 Feat/360
  app/cover-letter/page.tsx
  components/AuthButton.tsx
  components/CoverLetterForm.tsx
  components/cover-letter.tsx
  components/ui/form.tsx
  components/ui/label.tsx
  components/ui/textarea.tsx
  package-lock.json
  package.json
Labels: GSSoC'24, level3, gssoc

#354 Fix: Testimonial link on Leaderboard page does not navigate to the Testimonial page
  components/navbar.tsx
Labels: GSSoC'24, level1, gssoc

#388 Feat/377
  .env.example
  components/CoverLetterForm.tsx
  components/cover-letter.tsx
  package-lock.json
  package.json
  utils/Gemini.ts
Labels: GSSoC'24, level3, gssoc

#411 Preloader added
  components/new-resume.tsx
  components/ui/skeleton.tsx
Labels: GSSoC'24, level2, gssoc
