Repository ashutosh-rath02/git-re, pull requests merged in 2024-05, with the labels that each got.

#57 Recent profiles
  .env.example
  app/api/users/route.ts
  app/page.tsx
  components/Form.tsx
  components/RecentGenerations.tsx
  components/ui/avatar.tsx
  components/ui/card-hover-effect.tsx
  package-lock.json
  package.json
  tailwind.config.ts
  types/index.ts
  utils/cn.ts
  utils/config/db.ts
  utils/models/UserModel.ts
Labels: GSSoC'24, Level 3, gssoc

#64 style: 💄 In resume preview page, sidebar is sticky now. ✅ Closes: #61
  app/layout.tsx
  components/Sidebar.tsx
Labels: GSSoC'24, level1, gssoc

#65 feat: added sharing feature for mulitple platforms
  .env.example
  app/api/og/route.tsx
  app/resume/[username]/page.tsx
  components/Resume.tsx
  components/ShareBtn.tsx
  components/ui/dialog.tsx
  package-lock.json
  package.json
Labels: GSSoC'24, level2, gssoc

#78 enhancement: redesigned Navbar and Footer
  app/page.tsx
  components/AuthButton.tsx
  components/footer.tsx
  components/navbar.tsx
  components/ui/button.tsx
  package-lock.json
  package.json
  tailwind.config.js
Labels: GSSoC'24, level2, gssoc

#92 Og image customization
  app/api/og/route.tsx
  app/resume/[username]/page.tsx
  components/navbar.tsx
  package-lock.json
  public/assets/Roboto-Bold.ttf
  public/assets/Roboto-Italic.ttf
Labels: GSSoC'24, level2, gssoc

#98 DOCS - added table of contents and featured in section
  .github/assets/gssoc24.png
  README.md
Labels: GSSoC'24, level1, gssoc

#101 Update README.md
  README.md
Labels: GSSoC'24, level1, gssoc

#110 [FIX] - Fixed the responsiveness of UserData and Testimonial Section.
  app/page.tsx
  components/RecentGenerations.tsx
  components/UserTestimonials.tsx
Labels: GSSoC'24, level1, gssoc

#109 Updated README.md
  README.md
Labels: GSSoC'24, level1, gssoc

#120 Update LEARN.md
  LEARN.md
Labels: GSSoC'24, level1, gssoc

#94 Validation added for searching for a github username
  components/Form.tsx
Labels: GSSoC'24, level2, gssoc

#97 Fixed wrong re-direction of portfolio link on Resume page
  components/Resume.tsx
Labels: GSSoC'24, level2, gssoc

#126 fix:fixed the username not found bug
  components/Form.tsx
Labels: GSSoC'24, level2, gssoc

#124 fixed: recent users error handling and loading state
  app/api/users/route.ts
  components/RecentGenerations.tsx
Labels: GSSoC'24, level1, gssoc

#139 Hyperlinks Adjusted in the Important Links Sub Section
  components/footer.tsx
Labels: GSSoC'24, level1, gssoc

#158 fix: error due to missing blog url
  components/Resume.tsx
Labels: GSSoC'24, level2, gssoc

#167 added workflow as per issue #162
  .github/workflows/autocomment-iss-close.yml
Labels: GSSoC'24, level1, gssoc

#164 [FEAT]: Created Issue forms and made the issue options more visually appealing
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_update.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: GSSoC'24, level2, gssoc

#169 added workflow as per issue #163
  .github/workflows/autocomment-pr-raise.yml
Labels: GSSoC'24, level1, gssoc

#174 Added issue template for documentation issues
  .github/ISSUE_TEMPLATE/documentation.md
Labels: GSSoC'24, level2, gssoc

#173 Added feature to auto comment on pr merged
  .github/workflows/auto-comment-on-pr-merge.yml
Labels: GSSoC'24, level2, gssoc

#184 [feat]: add rating system for resume
  LEARN.md
  components/Resume.tsx
  components/StatsBox.tsx
  utils/rating/action.ts
  utils/resumeUtils.ts
Labels: GSSoC'24, level3, gssoc

#189 refactored: Transition Landing Page from Server-Side to Client-Side Rendering
  app/page.tsx
Labels: GSSoC'24, level2, gssoc

#200 fixed the responsivness of website
  app/layout.tsx
Labels: GSSoC'24, level1, gssoc

#202 refactor: redundant tailwind config file
  tailwind.config.js
  tailwind.config.ts
Labels: GSSoC'24, level1, gssoc

#201 made navbar responsive
  components/Hamburger.tsx
  components/navbar.tsx
Labels: GSSoC'24, level2, gssoc
